import type {
  Announcement,
  AppNotification,
  AuditLogEntry,
  BackupRecord,
  DocumentItem,
  ExitRequest,
  LedgerTransaction,
  Meeting,
  PayrollImportSummary,
  RolePolicy,
  ShareWithdrawalRequest,
  SubscriptionPlan,
} from "@/lib/types";
import { MOCK_TODAY } from "./financials";
import { ORGANIZATION } from "./organization";

function addDays(iso: string, delta: number) {
  const d = new Date(iso);
  d.setDate(d.getDate() + delta);
  return d.toISOString().slice(0, 10);
}

export const MEETINGS: Meeting[] = [
  {
    id: "mtg-1",
    title: "Q3 General Assembly",
    date: addDays(MOCK_TODAY, 12),
    time: "14:00",
    location: "Karongi District Hall",
    agenda: [
      "Review of Q2 financial performance",
      "Loan portfolio update",
      "Approval of new membership applications",
      "AOB",
    ],
    status: "upcoming",
    attendeeIds: [],
    createdBy: "Jean Baptiste Habimana",
  },
  {
    id: "mtg-2",
    title: "Loan Committee Monthly Review",
    date: addDays(MOCK_TODAY, 5),
    time: "10:00",
    location: "APUPEKA Boardroom",
    agenda: ["Review pending loan applications", "Risk assessment updates"],
    status: "upcoming",
    attendeeIds: ["u-nsengimana", "u-mukamana"],
    createdBy: "Jean Baptiste Habimana",
  },
  {
    id: "mtg-3",
    title: "Q2 General Assembly",
    date: addDays(MOCK_TODAY, -78),
    time: "14:00",
    location: "Karongi District Hall",
    agenda: [
      "Review of Q1 financial performance",
      "Election of new committee member",
      "AOB",
    ],
    status: "completed",
    attendeeIds: [
      "u-habimana",
      "u-uwase",
      "u-nsengimana",
      "u-mukamana",
      "u-byiringiro",
      "u-ingabire",
      "u-nkurunziza",
      "u-nyiraneza",
      "u-mugisha",
      "u-uwimana",
    ],
    minutesSummary:
      "Q1 financial performance was presented and approved. Alice Mukamana was elected to the Loan Committee. Members raised concerns about payroll import delays, which the Accountant committed to resolving within two weeks.",
    createdBy: "Jean Baptiste Habimana",
  },
  {
    id: "mtg-4",
    title: "Annual General Meeting 2025",
    date: addDays(MOCK_TODAY, -260),
    time: "09:00",
    location: "Karongi District Hall",
    agenda: [
      "Annual financial report",
      "Election of Secretary and Organization Admin",
      "Approval of 2026 loan policy revisions",
    ],
    status: "completed",
    attendeeIds: [
      "u-habimana",
      "u-uwase",
      "u-nsengimana",
      "u-mukamana",
      "u-byiringiro",
      "u-ingabire",
    ],
    minutesSummary:
      "Annual financial statements were approved unanimously. Jean Baptiste Habimana was re-elected Secretary and Grace Ingabire was elected Organization Admin. Revised loan policy (5% interest, 1% guaranteed-loan insurance) was ratified.",
    createdBy: "Jean Baptiste Habimana",
  },
];

export const ANNOUNCEMENTS: Announcement[] = [
  {
    id: "ann-1",
    title: "Payroll savings deduction schedule for August",
    body: "This month's salary savings deductions will be processed on 25th August following payroll release from the District Finance Office. Please ensure your bank details are up to date with HR.",
    date: addDays(MOCK_TODAY, -2),
    priority: "normal",
    author: "Eric Byiringiro",
    audience: "all",
  },
  {
    id: "ann-2",
    title: "Q3 General Assembly — 12 days from now",
    body: "All members are invited to the Q3 General Assembly at Karongi District Hall. Attendance will be recorded and is required for members with active loan applications.",
    date: addDays(MOCK_TODAY, -1),
    priority: "important",
    author: "Jean Baptiste Habimana",
    audience: "all",
  },
  {
    id: "ann-3",
    title: "Scheduled maintenance — system may be briefly unavailable",
    body: "IkiminaConnect will undergo routine maintenance on Sunday between 22:00 and 23:00. Some features may be briefly unavailable during this window.",
    date: addDays(MOCK_TODAY, -5),
    priority: "urgent",
    author: "Platform Operations",
    audience: "all",
  },
  {
    id: "ann-4",
    title: "Reminder: update your guarantor commitments",
    body: "Members currently guaranteeing an active loan cannot apply for a new loan until that guarantee is released. Check your Guarantor page for your current commitments.",
    date: addDays(MOCK_TODAY, -9),
    priority: "normal",
    author: "Emmanuel Nsengimana",
    audience: "members",
  },
];

export const DOCUMENTS: DocumentItem[] = [
  {
    id: "doc-1",
    name: "APUPEKA Cooperative Constitution (2025 Revision)",
    category: "constitution",
    fileType: "pdf",
    uploadedDate: "2025-01-14",
    uploadedBy: "Jean Baptiste Habimana",
    sizeKb: 842,
    visibility: "all",
  },
  {
    id: "doc-2",
    name: "Loan Policy — Interest, Insurance & Guarantor Rules",
    category: "policy",
    fileType: "pdf",
    uploadedDate: "2025-11-02",
    uploadedBy: "Emmanuel Nsengimana",
    sizeKb: 214,
    visibility: "all",
  },
  {
    id: "doc-3",
    name: "Savings & Shares Policy",
    category: "policy",
    fileType: "pdf",
    uploadedDate: "2025-11-02",
    uploadedBy: "Marie Claire Uwase",
    sizeKb: 176,
    visibility: "all",
  },
  {
    id: "doc-4",
    name: "Q2 2026 Financial Report",
    category: "report",
    fileType: "pdf",
    uploadedDate: addDays(MOCK_TODAY, -20),
    uploadedBy: "Marie Claire Uwase",
    sizeKb: 1120,
    visibility: "all",
  },
  {
    id: "doc-5",
    name: "Q2 General Assembly — Minutes",
    category: "minutes",
    fileType: "docx",
    uploadedDate: addDays(MOCK_TODAY, -77),
    uploadedBy: "Jean Baptiste Habimana",
    sizeKb: 98,
    visibility: "all",
  },
  {
    id: "doc-6",
    name: "Membership Application Form",
    category: "form",
    fileType: "docx",
    uploadedDate: "2024-06-01",
    uploadedBy: "Jean Baptiste Habimana",
    sizeKb: 54,
    visibility: "all",
  },
  {
    id: "doc-7",
    name: "Loan Application Form",
    category: "form",
    fileType: "docx",
    uploadedDate: "2024-06-01",
    uploadedBy: "Jean Baptiste Habimana",
    sizeKb: 61,
    visibility: "all",
  },
  {
    id: "doc-8",
    name: "Guarantor Consent Form",
    category: "form",
    fileType: "docx",
    uploadedDate: "2024-06-01",
    uploadedBy: "Jean Baptiste Habimana",
    sizeKb: 47,
    visibility: "all",
  },
  {
    id: "doc-9",
    name: "Board Risk & Compliance Report — July 2026",
    category: "report",
    fileType: "xlsx",
    uploadedDate: addDays(MOCK_TODAY, -6),
    uploadedBy: "Alice Mukamana",
    sizeKb: 312,
    visibility: "admins",
  },
];

export const POLICIES: RolePolicy[] = [
  {
    id: "pol-membership",
    title: "Membership Policy",
    category: "membership",
    summary:
      "Eligibility, registration, and identity verification requirements for new members.",
    body: [
      "Membership is open to all confirmed employees of the district and its affiliated institutions.",
      "Registration requires a valid National ID and Employee ID verified against the district's employee registry.",
      "The National ID is the member's unique identifier across the platform; the Employee ID remains unique within the organization.",
      "New members must complete a Membership Application Form, countersigned by the Secretary.",
    ],
    updatedAt: "2025-11-02",
  },
  {
    id: "pol-savings",
    title: "Savings Policy",
    category: "savings",
    summary:
      "How monthly, voluntary, and payroll-deducted savings are collected and recorded.",
    body: [
      "Monthly savings are deducted directly from salary through the district's HR payroll system and imported by the Accountant each month.",
      "Members may additionally make voluntary savings deposits at any time.",
      "All savings are recorded in the member's Savings Statement with a running balance, similar to a bank statement.",
      "Savings withdrawals are only permitted upon exit from the cooperative, subject to Organization Admin approval.",
    ],
    updatedAt: "2025-11-02",
  },
  {
    id: "pol-shares",
    title: "Shares Policy",
    category: "shares",
    summary: "Share pricing, purchases, and withdrawal rules.",
    body: [
      "Each share is valued at 5,000 RWF.",
      "Every member holds a minimum of 5 founding shares upon registration.",
      "Additional shares may be purchased at any time in whole-share increments.",
      "Share withdrawal requests are reviewed by the Organization Admin and are subject to available cooperative liquidity.",
    ],
    updatedAt: "2025-11-02",
  },
  {
    id: "pol-loan",
    title: "Loan Policy",
    category: "loan",
    summary: "Interest, insurance, eligibility, and repayment rules.",
    body: [
      "Members become eligible for a loan after a minimum of three months of continuous savings.",
      "Standard interest is 5% of the requested loan amount, applied once over the loan period.",
      "A 1% insurance fee applies only when the requested amount exceeds the member's total savings — this is exactly when a guarantor is required.",
      "If the requested amount is within the member's savings, no guarantor and no insurance fee are required.",
      "Repayment is deducted automatically from salary every month through HR payroll; there are no late-payment penalties since repayment is salary-based.",
      "Loan applications pass through: Submitted → Under Review → Guarantor Approval (if required) → Committee Review → Approved → Contract Generated → Disbursed → Repaying → Completed.",
    ],
    updatedAt: "2026-01-20",
  },
  {
    id: "pol-guarantor",
    title: "Guarantor Policy",
    category: "guarantor",
    summary: "Rules governing who can guarantee a loan and their obligations.",
    body: [
      "A guarantor must be an active member in good standing.",
      "A member actively guaranteeing another member's loan cannot apply for a new loan of their own until that guarantee is released.",
      "Guarantors are notified of the outstanding balance and status of loans they have guaranteed at all times.",
      "If a borrower defaults, the guarantor's savings may be used to cover the outstanding balance, subject to Loan Committee review.",
    ],
    updatedAt: "2025-11-02",
  },
  {
    id: "pol-suspension",
    title: "Suspension Policy",
    category: "suspension",
    summary: "Grounds and process for suspending a member.",
    body: [
      "Members may be suspended by the Organization Admin for repeated missed contributions, fraudulent activity, or violation of the cooperative constitution.",
      "Suspended members retain visibility of their savings and loan history but cannot apply for new loans, purchase shares, or vote at meetings.",
      "Suspension decisions may be appealed to the Board within 30 days.",
    ],
    updatedAt: "2025-09-10",
  },
  {
    id: "pol-exit",
    title: "Exit Policy",
    category: "exit",
    summary: "How members formally leave the cooperative and settle balances.",
    body: [
      "Members wishing to exit must submit a Membership Exit Request to the Secretary.",
      "All outstanding loan balances must be settled, or a repayment arrangement approved, before exit is finalized.",
      "Savings and share value are refunded within 30 days of an approved exit request.",
    ],
    updatedAt: "2025-09-10",
  },
  {
    id: "pol-privacy",
    title: "Privacy Policy",
    category: "privacy",
    summary: "How member data is collected, used, and protected.",
    body: [
      "Member financial data is only accessible to the member themselves and authorized organization officers (Secretary, Accountant, Loan Committee, Organization Admin) strictly for cooperative operations.",
      "Data is never shared with third parties without member consent, except where required by Rwandan law.",
      "Each organization's data is logically isolated from other organizations on the platform.",
    ],
    updatedAt: "2025-09-10",
  },
];

export const NOTIFICATIONS: AppNotification[] = [
  {
    id: "ntf-1",
    userId: "u-nkurunziza",
    title: "Loan application received",
    body: "Your loan application APK-2026-101 has been submitted and is awaiting review.",
    date: addDays(MOCK_TODAY, -3),
    read: false,
    type: "loan",
  },
  {
    id: "ntf-2",
    userId: "u-mugisha",
    title: "Guarantor request sent",
    body: "Clarisse Uwamahoro has been requested to guarantee your loan APK-2026-103.",
    date: addDays(MOCK_TODAY, -9),
    read: true,
    type: "loan",
  },
  {
    id: "ntf-3",
    userId: "u-uwamahoro",
    title: "You've been requested as a guarantor",
    body: "Robert Mugisha has requested you as a guarantor for a 2,000,000 RWF loan.",
    date: addDays(MOCK_TODAY, -9),
    read: false,
    type: "loan",
  },
  {
    id: "ntf-4",
    userId: "u-hakizimana",
    title: "Loan approved",
    body: "Your loan APK-2026-105 has been approved. Your contract is being prepared.",
    date: addDays(MOCK_TODAY, -2),
    read: false,
    type: "loan",
  },
  {
    id: "ntf-5",
    userId: "u-nkurunziza",
    title: "Q3 General Assembly scheduled",
    body: "The Q3 General Assembly will be held in 12 days at Karongi District Hall.",
    date: addDays(MOCK_TODAY, -1),
    read: false,
    type: "meeting",
  },
];

export const LEDGER_TRANSACTIONS: LedgerTransaction[] = [
  {
    id: "led-1",
    memberId: "u-niyonzima",
    type: "loan-disbursement-adjustment",
    amount: 1000000,
    date: addDays(MOCK_TODAY, -3),
    method: "bank-transfer",
    reference: "APK-2026-107",
    recordedBy: "Marie Claire Uwase",
  },
  {
    id: "led-2",
    memberId: "u-mukeshimana",
    type: "loan-repayment",
    amount: 66250,
    date: addDays(MOCK_TODAY, -10),
    method: "payroll",
    reference: "APK-2026-062 / Installment 5",
    recordedBy: "Marie Claire Uwase",
  },
  {
    id: "led-3",
    memberId: "u-bizimana",
    type: "loan-repayment",
    amount: 96250,
    date: addDays(MOCK_TODAY, -10),
    method: "payroll",
    reference: "APK-2025-071 / Installment 8",
    recordedBy: "Marie Claire Uwase",
  },
  {
    id: "led-4",
    memberId: "u-nyiraneza",
    type: "insurance-fee",
    amount: 22000,
    date: addDays(MOCK_TODAY, -6),
    method: "payroll",
    reference: "APK-2026-102 / Insurance",
    recordedBy: "Marie Claire Uwase",
  },
  {
    id: "led-5",
    memberId: "u-hakizimana",
    type: "interest-income",
    amount: 60000,
    date: addDays(MOCK_TODAY, -2),
    method: "payroll",
    reference: "APK-2026-105 / Interest",
    recordedBy: "Marie Claire Uwase",
  },
];

export const PAYROLL_IMPORTS: PayrollImportSummary[] = [
  {
    id: "imp-1",
    fileName: "payroll_savings_july2026.xlsx",
    importedBy: "Marie Claire Uwase",
    date: addDays(MOCK_TODAY, -32),
    totalRecords: 21,
    successful: 21,
    failed: 0,
    duplicates: 0,
    totalAmount: 5850000,
  },
  {
    id: "imp-2",
    fileName: "payroll_savings_june2026.xlsx",
    importedBy: "Marie Claire Uwase",
    date: addDays(MOCK_TODAY, -62),
    totalRecords: 21,
    successful: 19,
    failed: 2,
    duplicates: 0,
    totalAmount: 5320000,
  },
  {
    id: "imp-3",
    fileName: "payroll_savings_may2026.xlsx",
    importedBy: "Marie Claire Uwase",
    date: addDays(MOCK_TODAY, -93),
    totalRecords: 20,
    successful: 20,
    failed: 0,
    duplicates: 1,
    totalAmount: 5100000,
  },
];

export const AUDIT_LOGS: AuditLogEntry[] = [
  {
    id: "aud-1",
    actor: "Grace Ingabire",
    action: "Suspended member",
    target: "Yvonne Mukamurenzi (EMP020)",
    date: addDays(MOCK_TODAY, -18),
    organizationId: ORGANIZATION.id,
  },
  {
    id: "aud-2",
    actor: "Emmanuel Nsengimana",
    action: "Rejected loan application",
    target: "Josiane Umutoni — APK-2026-058",
    date: addDays(MOCK_TODAY, -50),
    organizationId: ORGANIZATION.id,
  },
  {
    id: "aud-3",
    actor: "Marie Claire Uwase",
    action: "Imported payroll savings",
    target: "payroll_savings_july2026.xlsx (21 records)",
    date: addDays(MOCK_TODAY, -32),
    organizationId: ORGANIZATION.id,
  },
  {
    id: "aud-4",
    actor: "Patrick Twagirayezu",
    action: "Approved organization onboarding",
    target: "Musanze Teachers SACCO",
    date: "2023-09-12",
    organizationId: "platform",
  },
  {
    id: "aud-5",
    actor: "Patrick Twagirayezu",
    action: "Suspended organization",
    target: "Nyagatare Farmers Cooperative — billing overdue",
    date: addDays(MOCK_TODAY, -15),
    organizationId: "platform",
  },
];

export const BACKUPS: BackupRecord[] = [
  {
    id: "bkp-1",
    organizationId: ORGANIZATION.id,
    label: "Scheduled nightly backup",
    date: addDays(MOCK_TODAY, -1),
    sizeMb: 84,
    type: "scheduled",
  },
  {
    id: "bkp-2",
    organizationId: ORGANIZATION.id,
    label: "Pre-payroll-import manual backup",
    date: addDays(MOCK_TODAY, -32),
    sizeMb: 81,
    type: "manual",
  },
  {
    id: "bkp-3",
    organizationId: "platform",
    label: "Platform-wide scheduled backup",
    date: addDays(MOCK_TODAY, -1),
    sizeMb: 962,
    type: "scheduled",
  },
];

export const EXIT_REQUESTS: ExitRequest[] = [
  {
    id: "exit-1",
    memberId: "u-kwizera",
    reason: "Relocating to Kigali for a new position outside the district.",
    requestedDate: addDays(MOCK_TODAY, -4),
    status: "pending",
  },
];

export const SHARE_WITHDRAWALS: ShareWithdrawalRequest[] = [
  {
    id: "wdr-1",
    memberId: "u-habyarimana",
    shares: 4,
    amount: 20000,
    requestedDate: addDays(MOCK_TODAY, -8),
    status: "pending",
  },
];

export const SUBSCRIPTION_PLANS: SubscriptionPlan[] = [
  {
    id: "plan-starter",
    name: "Starter",
    priceMonthlyRwf: 49000,
    maxMembers: 50,
    features: [
      "Up to 50 members",
      "Savings & shares management",
      "Loan workflow & contracts",
      "Email support",
    ],
  },
  {
    id: "plan-growth",
    name: "Growth",
    priceMonthlyRwf: 129000,
    maxMembers: 200,
    features: [
      "Up to 200 members",
      "Everything in Starter",
      "Excel payroll import",
      "Advanced reports & analytics",
      "Priority support",
    ],
  },
  {
    id: "plan-enterprise",
    name: "Enterprise",
    priceMonthlyRwf: 349000,
    maxMembers: 2000,
    features: [
      "Unlimited members",
      "Everything in Growth",
      "Multi-branch support",
      "Custom branding",
      "Dedicated account manager",
      "SLA-backed uptime",
    ],
  },
];
