import type { Organization } from "@/lib/types";

export const ORGANIZATION: Organization = {
  id: "org-apupeka",
  name: "APUPEKA Digital Savings and Loan Cooperative",
  shortName: "APUPEKA",
  slug: "apupeka",
  district: "Karongi",
  sector: "Bwishyura",
  address: "Karongi District Offices, Western Province, Rwanda",
  contactEmail: "info@apupeka.rw",
  contactPhone: "+250 788 123 456",
  logoInitials: "AP",
  brandColor: "#2563eb",
  stampLabel: "APUPEKA SACCO — OFFICIAL STAMP",
  plan: "growth",
  memberCount: 22,
  createdAt: "2021-03-01",
  status: "active",
};

// Other tenants on the platform, for the Super Admin workspace.
export const PLATFORM_ORGANIZATIONS: Organization[] = [
  ORGANIZATION,
  {
    id: "org-musanze-teachers",
    name: "Musanze Teachers SACCO",
    shortName: "MTS",
    slug: "musanze-teachers",
    district: "Musanze",
    sector: "Muhoza",
    address: "Musanze District Offices, Northern Province, Rwanda",
    contactEmail: "info@musanzeteachers.rw",
    contactPhone: "+250 788 234 567",
    logoInitials: "MT",
    brandColor: "#0ea5e9",
    stampLabel: "MUSANZE TEACHERS SACCO — OFFICIAL STAMP",
    plan: "starter",
    memberCount: 64,
    createdAt: "2023-09-12",
    status: "active",
  },
  {
    id: "org-huye-health",
    name: "Huye Health Workers Cooperative",
    shortName: "HHWC",
    slug: "huye-health",
    district: "Huye",
    sector: "Ngoma",
    address: "Huye District Offices, Southern Province, Rwanda",
    contactEmail: "info@huyehealth.rw",
    contactPhone: "+250 788 345 678",
    logoInitials: "HH",
    brandColor: "#10b981",
    stampLabel: "HUYE HEALTH WORKERS COOPERATIVE — OFFICIAL STAMP",
    plan: "enterprise",
    memberCount: 138,
    createdAt: "2020-11-04",
    status: "active",
  },
  {
    id: "org-rubavu-traders",
    name: "Rubavu Traders Savings Group",
    shortName: "RTSG",
    slug: "rubavu-traders",
    district: "Rubavu",
    sector: "Gisenyi",
    address: "Rubavu District Offices, Western Province, Rwanda",
    contactEmail: "info@rubavutraders.rw",
    contactPhone: "+250 788 456 789",
    logoInitials: "RT",
    brandColor: "#f59e0b",
    stampLabel: "RUBAVU TRADERS SAVINGS GROUP — OFFICIAL STAMP",
    plan: "starter",
    memberCount: 41,
    createdAt: "2024-02-20",
    status: "trial",
  },
  {
    id: "org-nyagatare-farmers",
    name: "Nyagatare Farmers Cooperative",
    shortName: "NFC",
    slug: "nyagatare-farmers",
    district: "Nyagatare",
    sector: "Rukomo",
    address: "Nyagatare District Offices, Eastern Province, Rwanda",
    contactEmail: "info@nyagatarefarmers.rw",
    contactPhone: "+250 788 567 890",
    logoInitials: "NF",
    brandColor: "#8b5cf6",
    stampLabel: "NYAGATARE FARMERS COOPERATIVE — OFFICIAL STAMP",
    plan: "growth",
    memberCount: 97,
    createdAt: "2022-06-18",
    status: "suspended",
  },
];
